name: manage-azure-policy-0bf88112
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/CORS_should_not_allow_every_resource_to_access_your_Function_Apps_0820b7b9-23aa-4725-a1ce-ae4558f718e5/**'
#      - 'policies/Ensure_API_app_has_Client_Certificates_(Incoming_client_certificates)_set_to_On_0c192fe8-9cbb-4516-85b3-0ade8bd03886/**'
#      - 'policies/Managed_identity_should_be_used_in_your_Function_App_0da106f2-4ca3-48e8-bc85-c638fe6aea8f/**'
#      - 'policies/Remote_debugging_should_be_turned_off_for_Function_Apps_0e60b895-3786-45da-8377-9c6b4b6ac5f9/**'
#      - 'policies/Ensure_that_PHP_version_is_the_latest,_if_used_as_a_part_of_the_API_app_1bc1795e-d44a-4d48-9b3b-6fff0fd5f9ba/**'
#      - 'policies/Managed_identity_should_be_used_in_your_Web_App_2b9ad585-36bc-4615-b300-fd4435808332/**'
#      - 'policies/App_Service_Environment_apps_should_not_be_reachable_over_public_internet_2d048aca-6479-4923-88f5-e2ac295d9af3/**'
#      - 'policies/API_apps_should_use_an_Azure_file_share_for_its_content_directory_324c7761-08db-4474-9661-d1039abc92ee/**'
#      - 'policies/App_Service_apps_should_enable_outbound_non-RFC_1918_traffic_to_Azure_Virtual_Network_33228571-70a4-4fa1-8ca1-26d0aba8d6ef/**'
#      - 'policies/CORS_should_not_allow_every_resource_to_access_your_API_App_358c20a6-3f9e-4f0e-97ff-c6ce485e2aac/**'
#      - 'policies/Ensure_that_Java_version_is_the_latest,_if_used_as_a_part_of_the_Web_app_496223c3-ad65-4ecd-878a-bae78737e9ed/**'
#      - 'policies/Function_apps_should_use_an_Azure_file_share_for_its_content_directory_4d0bc837-6eff-477e-9ecd-33bf8d4212a5/**'
#      - 'policies/FTPS_should_be_required_in_your_Web_App_4d24b6d4-5e53-4a4f-a7f4-618fa573ee4b/**'
#      - 'policies/CORS_should_not_allow_every_resource_to_access_your_Web_Applications_5744710e-cc2f-4ee8-8809-3b11e89f4bc9/**'
#      - 'policies/Ensure_WEB_app_has_Client_Certificates_(Incoming_client_certificates)_set_to_On_5bb220d9-2698-4ee4-8404-b9c30c9df609/**'
#      - 'policies/App_Services_should_disable_public_network_access_63a0ac64-5d5f-4569-8a3d-df67cc1ce9d7/**'
#      - 'policies/Function_App_should_only_be_accessible_over_HTTPS_6d555dd1-86f2-4f1c-8ed7-5abae7c6cbab/**'
#      - 'policies/Ensure_that_Python_version_is_the_latest,_if_used_as_a_part_of_the_Web_app_7008174a-fd10-4ef0-817e-fc820a951d73/**'
#      - 'policies/Ensure_that_PHP_version_is_the_latest,_if_used_as_a_part_of_the_WEB_app_7261b898-8a84-4db8-9e04-18527132abb3/**'
#      - 'policies/Ensure_that_Python_version_is_the_latest,_if_used_as_a_part_of_the_Function_app_7238174a-fd10-4ef0-817e-fc820a951d73/**'
#      - 'policies/App_Service_Apps_should_be_injected_into_a_virtual_network_72d04c29-f87d-4575-9731-419ff16a2757/**'
#      - 'policies/Ensure_that_Python_version_is_the_latest,_if_used_as_a_part_of_the_API_app_74c3584d-afae-46f7-a20a-6f8adba71a16/**'
#      - 'policies/Configure_App_Services_to_disable_public_network_access_81dff7c0-4020-4b58-955d-c076a2136b56/**'
#      - 'policies/App_Service_Environment_should_be_configured_with_strongest_TLS_Cipher_suites_817dcf37-e83d-4999-a472-644eada2ea1e/**'
#      - 'policies/Ensure_that_Java_version_is_the_latest,_if_used_as_a_part_of_the_API_app_88999f4c-376a-45c8-bcb3-4058f713cf39/**'
#      - 'policies/Ensure_that_HTTP_Version_is_the_latest,_if_used_to_run_the_Web_app_8c122334-9d20-4eb8-89ea-ac9a705b74ae/**'
#      - 'policies/Latest_TLS_version_should_be_used_in_your_API_App_8cb6aa8b-9e41-4f4e-aa25-089a7ac2581e/**'
#      - 'policies/Resource_logs_in_App_Services_should_be_enabled_91a78b24-f231-4a8a-8da9-02c35b2b6510/**'
#      - 'policies/Authentication_should_be_enabled_on_your_web_app_95bccee9-a7f8-4bec-9ee9-62c3473701fc/**'
#      - 'policies/Ensure_that_HTTP_Version_is_the_latest,_if_used_to_run_the_API_app_991310cd-e9f3-47bc-b7b6-f57b557d07db/**'
#      - 'policies/FTPS_only_should_be_required_in_your_API_App_9a1b8c48-453a-4044-86c3-d8bfd823e4f5/**'
#      - 'policies/Ensure_that_Java_version_is_the_latest,_if_used_as_a_part_of_the_Function_app_9d0b6ea4-93e2-4578-bf2f-6bb17d22b4bc/**'
#      - 'policies/Configure_App_Services_to_use_private_DNS_zones_b318f84a-b872-429b-ac6d-a01b96814452/**'
#      - 'policies/Diagnostic_logs_in_App_Services_should_be_enabled_b607c5de-e7d9-4eee-9e5c-83f1bcee4fa0/**'
#      - 'policies/API_App_should_only_be_accessible_over_HTTPS_b7ddfbdc-1260-477d-91fd-98bd9be789a6/**'
#      - 'policies/Managed_identity_should_be_used_in_your_API_App_c4d441f8-f9d9-4a9e-9cef-e82117cb3eef/**'
#      - 'policies/Authentication_should_be_enabled_on_your_API_app_c4ebc54a-46e1-481a-bee2-d4411e95d828/**'
#      - 'policies/Authentication_should_be_enabled_on_your_Function_app_c75248c1-ea1d-4a9c-8fc9-29a6aabd5da8/**'
#      - 'policies/Remote_debugging_should_be_turned_off_for_Web_Applications_cb510bfd-1cba-4d9f-a230-cb0976f4bb71/**'
#      - 'policies/App_Service_Environment_should_disable_TLS_1.0_and_1.1_d6545c6b-dd9d-4265-91e6-0b451e2f1c50/**'
#      - 'policies/Web_apps_should_use_an_Azure_file_share_for_its_content_directory_dcbc65aa-59f3-4239-8978-3bb869d82604/**'
#      - 'policies/Ensure_that_HTTP_Version_is_the_latest,_if_used_to_run_the_Function_app_e2c1c086-2d84-4019-bff3-c44ccd95113c/**'
#      - 'policies/Remote_debugging_should_be_turned_off_for_API_Apps_e9c8d085-d9cc-4b17-9cdc-059f1f01f19e/**'
#      - 'policies/Function_apps_should_have_Client_Certificates_(Incoming_client_certificates)_enabled_eaebaea7-8013-4ceb-9d14-7eb32271373c/**'
#      - 'policies/App_Service_Environment_should_be_provisioned_with_latest_versions_eb4d34ab-0929-491c-bbf3-61e13da19f9a/**'
#      - 'policies/Latest_TLS_version_should_be_used_in_your_Web_App_f0e6e85b-9b9f-4a4b-b67b-f730d42f1b0b/**'
#      - 'policies/Latest_TLS_version_should_be_used_in_your_Function_App_f9d614c5-c173-4d56-95a7-b4437057d193/**'
#      - 'policies/App_Service_Environment_should_enable_internal_encryption_fb74e86f-d351-4b8d-b034-93da7391c01f/**'
#      - 'policies/FTPS_only_should_be_required_in_your_Function_App_399b2637-a50f-4f95-96f8-3a145476eb15/**'
#      - .github/workflows/manage-azure-policy-0bf88112.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_0bf88112}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/CORS_should_not_allow_every_resource_to_access_your_Function_Apps_0820b7b9-23aa-4725-a1ce-ae4558f718e5/**
          policies/Ensure_API_app_has_Client_Certificates_(Incoming_client_certificates)_set_to_On_0c192fe8-9cbb-4516-85b3-0ade8bd03886/**
          policies/Managed_identity_should_be_used_in_your_Function_App_0da106f2-4ca3-48e8-bc85-c638fe6aea8f/**
          policies/Remote_debugging_should_be_turned_off_for_Function_Apps_0e60b895-3786-45da-8377-9c6b4b6ac5f9/**
          policies/Ensure_that_PHP_version_is_the_latest,_if_used_as_a_part_of_the_API_app_1bc1795e-d44a-4d48-9b3b-6fff0fd5f9ba/**
          policies/Managed_identity_should_be_used_in_your_Web_App_2b9ad585-36bc-4615-b300-fd4435808332/**
          policies/App_Service_Environment_apps_should_not_be_reachable_over_public_internet_2d048aca-6479-4923-88f5-e2ac295d9af3/**
          policies/API_apps_should_use_an_Azure_file_share_for_its_content_directory_324c7761-08db-4474-9661-d1039abc92ee/**
          policies/App_Service_apps_should_enable_outbound_non-RFC_1918_traffic_to_Azure_Virtual_Network_33228571-70a4-4fa1-8ca1-26d0aba8d6ef/**
          policies/CORS_should_not_allow_every_resource_to_access_your_API_App_358c20a6-3f9e-4f0e-97ff-c6ce485e2aac/**
          policies/Ensure_that_Java_version_is_the_latest,_if_used_as_a_part_of_the_Web_app_496223c3-ad65-4ecd-878a-bae78737e9ed/**
          policies/Function_apps_should_use_an_Azure_file_share_for_its_content_directory_4d0bc837-6eff-477e-9ecd-33bf8d4212a5/**
          policies/FTPS_should_be_required_in_your_Web_App_4d24b6d4-5e53-4a4f-a7f4-618fa573ee4b/**
          policies/CORS_should_not_allow_every_resource_to_access_your_Web_Applications_5744710e-cc2f-4ee8-8809-3b11e89f4bc9/**
          policies/Ensure_WEB_app_has_Client_Certificates_(Incoming_client_certificates)_set_to_On_5bb220d9-2698-4ee4-8404-b9c30c9df609/**
          policies/App_Services_should_disable_public_network_access_63a0ac64-5d5f-4569-8a3d-df67cc1ce9d7/**
          policies/Function_App_should_only_be_accessible_over_HTTPS_6d555dd1-86f2-4f1c-8ed7-5abae7c6cbab/**
          policies/Ensure_that_Python_version_is_the_latest,_if_used_as_a_part_of_the_Web_app_7008174a-fd10-4ef0-817e-fc820a951d73/**
          policies/Ensure_that_PHP_version_is_the_latest,_if_used_as_a_part_of_the_WEB_app_7261b898-8a84-4db8-9e04-18527132abb3/**
          policies/Ensure_that_Python_version_is_the_latest,_if_used_as_a_part_of_the_Function_app_7238174a-fd10-4ef0-817e-fc820a951d73/**
          policies/App_Service_Apps_should_be_injected_into_a_virtual_network_72d04c29-f87d-4575-9731-419ff16a2757/**
          policies/Ensure_that_Python_version_is_the_latest,_if_used_as_a_part_of_the_API_app_74c3584d-afae-46f7-a20a-6f8adba71a16/**
          policies/Configure_App_Services_to_disable_public_network_access_81dff7c0-4020-4b58-955d-c076a2136b56/**
          policies/App_Service_Environment_should_be_configured_with_strongest_TLS_Cipher_suites_817dcf37-e83d-4999-a472-644eada2ea1e/**
          policies/Ensure_that_Java_version_is_the_latest,_if_used_as_a_part_of_the_API_app_88999f4c-376a-45c8-bcb3-4058f713cf39/**
          policies/Ensure_that_HTTP_Version_is_the_latest,_if_used_to_run_the_Web_app_8c122334-9d20-4eb8-89ea-ac9a705b74ae/**
          policies/Latest_TLS_version_should_be_used_in_your_API_App_8cb6aa8b-9e41-4f4e-aa25-089a7ac2581e/**
          policies/Resource_logs_in_App_Services_should_be_enabled_91a78b24-f231-4a8a-8da9-02c35b2b6510/**
          policies/Authentication_should_be_enabled_on_your_web_app_95bccee9-a7f8-4bec-9ee9-62c3473701fc/**
          policies/Ensure_that_HTTP_Version_is_the_latest,_if_used_to_run_the_API_app_991310cd-e9f3-47bc-b7b6-f57b557d07db/**
          policies/FTPS_only_should_be_required_in_your_API_App_9a1b8c48-453a-4044-86c3-d8bfd823e4f5/**
          policies/Ensure_that_Java_version_is_the_latest,_if_used_as_a_part_of_the_Function_app_9d0b6ea4-93e2-4578-bf2f-6bb17d22b4bc/**
          policies/Configure_App_Services_to_use_private_DNS_zones_b318f84a-b872-429b-ac6d-a01b96814452/**
          policies/Diagnostic_logs_in_App_Services_should_be_enabled_b607c5de-e7d9-4eee-9e5c-83f1bcee4fa0/**
          policies/API_App_should_only_be_accessible_over_HTTPS_b7ddfbdc-1260-477d-91fd-98bd9be789a6/**
          policies/Managed_identity_should_be_used_in_your_API_App_c4d441f8-f9d9-4a9e-9cef-e82117cb3eef/**
          policies/Authentication_should_be_enabled_on_your_API_app_c4ebc54a-46e1-481a-bee2-d4411e95d828/**
          policies/Authentication_should_be_enabled_on_your_Function_app_c75248c1-ea1d-4a9c-8fc9-29a6aabd5da8/**
          policies/Remote_debugging_should_be_turned_off_for_Web_Applications_cb510bfd-1cba-4d9f-a230-cb0976f4bb71/**
          policies/App_Service_Environment_should_disable_TLS_1.0_and_1.1_d6545c6b-dd9d-4265-91e6-0b451e2f1c50/**
          policies/Web_apps_should_use_an_Azure_file_share_for_its_content_directory_dcbc65aa-59f3-4239-8978-3bb869d82604/**
          policies/Ensure_that_HTTP_Version_is_the_latest,_if_used_to_run_the_Function_app_e2c1c086-2d84-4019-bff3-c44ccd95113c/**
          policies/Remote_debugging_should_be_turned_off_for_API_Apps_e9c8d085-d9cc-4b17-9cdc-059f1f01f19e/**
          policies/Function_apps_should_have_Client_Certificates_(Incoming_client_certificates)_enabled_eaebaea7-8013-4ceb-9d14-7eb32271373c/**
          policies/App_Service_Environment_should_be_provisioned_with_latest_versions_eb4d34ab-0929-491c-bbf3-61e13da19f9a/**
          policies/Latest_TLS_version_should_be_used_in_your_Web_App_f0e6e85b-9b9f-4a4b-b67b-f730d42f1b0b/**
          policies/Latest_TLS_version_should_be_used_in_your_Function_App_f9d614c5-c173-4d56-95a7-b4437057d193/**
          policies/App_Service_Environment_should_enable_internal_encryption_fb74e86f-d351-4b8d-b034-93da7391c01f/**
          policies/FTPS_only_should_be_required_in_your_Function_App_399b2637-a50f-4f95-96f8-3a145476eb15/**
